---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: default
spec:
  encryptedData:
    WEBPASSWORD: AgB9OsxIkv5106pMwtT6M28G3Yl+ITwQk5XHMVOM5slHlbTLdWiNMxV+lfggUNoOOBsvoulIstM7td0z+BXlJK+e6T9trXXm0lTLT6MppoySmofKT/tz9SKKaqlqjmHBNl/10oFt1V76BC/W7wRAUKUKYbAp0Hm8zw9uYWYIfm5sConVtVdEe+DKbD7DQQz7UGtgP68LRrTRv50qukS7N0a44PD67nx7PD/qreuNm+JWw9yqlrpfiJmB9Fp01W1fIXQy3+h+VJPqMz9xpoaOi4wJvTCDx9UcORzNbGFTW1G0vNdCkIc1FPvKsasQKiwyZkYRjRQr8ZmjSMatqAeeeOcvEPfP2hMTlhBKJpFGclP/NVLjllFGONgxL1sOihwhV1L71QhoxFMHohwQUigjezWOiDbrHbnVyKO1Pv0Mu5JBbX171iyXV61w//lyFH8cPIACM339T6cjMKE/EeRUNUgMCPqWu+b2uVUwTeP707ZSfQ9+EvrEOUefkV9eb5jhDa8V0qdJzODxWTut8Cllm6Hx9lKLDBgA0x/YY39y2lRpsRcJAfNSLW5heF59zOTTX3YHCeeA+ifR8XKv6AKY6WoWtW6pjDAGO+r3YgDLvOejQFN+WeN/EOf4wRBWkRn0ll7H8ytw3XyWHHZDzjVB6vVugK0gvkXzYzvJnvW26ygG45qh0HpzgFQELA/75tXyY0OT3RKgF3Ra3AI/jsML
  template:
    metadata:
      name: pihole-secret
      namespace: default
    type: Opaque
